app_id: 292e71ae-61e0-439a-8310-20d2febca33d
publisher_name: Alex Pototskiy
publisher_url: https://github.com/pavru/OneXray
display_name: BhsXRay
executable_name: BhsXRay.exe
script_template: inno_setup.iss
create_desktop_icon: true
setup_icon_file: windows\runner\resources\app_icon.ico
install_dir_name: '{autopf}\BhsXRay'
privileges_required: lowest
architectures_allowed: x64os
architectures_install_in_64bit_mode: x64os
locales:
  - en
